setLanguageFromWebBrowser();
loadSettings();
updateDocumentTitle();
markCurrentPageLink();
removeHrefAttributesFromLanguageButtons();
displayElementsForJSPageVersion();
displayCalendar();
sortProjectsByUpdate();
displayCookies();